"""test db migration from render(back to origin)

Revision ID: 23b22aab164a
Revises: a82e40f08b8b
Create Date: 2025-11-16 23:19:19.385507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b22aab164a'
down_revision: Union[str, Sequence[str], None] = 'a82e40f08b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.drop_column('documents', 'file_size_hehe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_hehe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
