"""test db migration from render

Revision ID: a82e40f08b8b
Revises: c53ce6e91060
Create Date: 2025-11-16 23:17:31.913702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82e40f08b8b'
down_revision: Union[str, Sequence[str], None] = 'c53ce6e91060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_hehe', sa.Integer(), nullable=False))
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_size_hehe')
    # ### end Alembic commands ###
