"""modify eeee

Revision ID: c53ce6e91060
Revises: a9641dd33afa
Create Date: 2025-11-12 22:59:17.513628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53ce6e91060'
down_revision: Union[str, Sequence[str], None] = 'a9641dd33afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.drop_column('documents', 'file_size_hehe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_hehe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
