"""add datatable for review quiz

Revision ID: 3a93b84e9e5d
Revises: 51412845a3d2
Create Date: 2025-12-24 04:21:53.818107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a93b84e9e5d'
down_revision: Union[str, Sequence[str], None] = '51412845a3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_quiz_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=False),
    sa.Column('total_original_attempts', sa.Integer(), nullable=False),
    sa.Column('original_avg_score', sa.Float(), nullable=False),
    sa.Column('review_score', sa.Float(), nullable=False),
    sa.Column('improvement_percentage', sa.Float(), nullable=False),
    sa.Column('improved_count', sa.Integer(), nullable=True),
    sa.Column('regressed_count', sa.Integer(), nullable=True),
    sa.Column('persistent_weak_count', sa.Integer(), nullable=True),
    sa.Column('consistent_strong_count', sa.Integer(), nullable=True),
    sa.Column('topic_breakdown', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('analysis_generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_session_id')
    )
    op.create_index(op.f('ix_review_quiz_analysis_course_id'), 'review_quiz_analysis', ['course_id'], unique=False)
    op.create_index(op.f('ix_review_quiz_analysis_id'), 'review_quiz_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_review_quiz_analysis_user_id'), 'review_quiz_analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_quiz_analysis_user_id'), table_name='review_quiz_analysis')
    op.drop_index(op.f('ix_review_quiz_analysis_id'), table_name='review_quiz_analysis')
    op.drop_index(op.f('ix_review_quiz_analysis_course_id'), table_name='review_quiz_analysis')
    op.drop_table('review_quiz_analysis')
    # ### end Alembic commands ###
