"""add index to course

Revision ID: 3f71d7c44383
Revises: 92ccb40e1461
Create Date: 2026-01-08 20:31:51.943552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f71d7c44383'
down_revision: Union[str, Sequence[str], None] = '92ccb40e1461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_course_desc_trgm', 'courses', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('ix_course_title_trgm', 'courses', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_title_trgm', table_name='courses', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('ix_course_desc_trgm', table_name='courses', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
