"""add datatable for review quiz

Revision ID: 51412845a3d2
Revises: 598d2029a739
Create Date: 2025-12-24 04:19:43.249470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51412845a3d2'
down_revision: Union[str, Sequence[str], None] = '598d2029a739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('session_type', sa.String(length=50), nullable=True))
    op.add_column('quiz_sessions', sa.Column('selected_quiz_ids', sa.String(), nullable=True))
    op.add_column('quiz_sessions', sa.Column('generated_questions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'generated_questions')
    op.drop_column('quiz_sessions', 'selected_quiz_ids')
    op.drop_column('quiz_sessions', 'session_type')
    # ### end Alembic commands ###
