"""remove document_id from conversation table

Revision ID: 598d2029a739
Revises: 4534efcdfdfa
Create Date: 2025-12-18 02:22:15.587587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598d2029a739'
down_revision: Union[str, Sequence[str], None] = '4534efcdfdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_document_id'), table_name='conversations')
    op.drop_constraint(op.f('conversations_document_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('conversations_document_id_fkey'), 'conversations', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversations_document_id'), 'conversations', ['document_id'], unique=False)
    # ### end Alembic commands ###
