"""add session_id to quiz

Revision ID: 6298d02803fa
Revises: 3dd25ab8d65d
Create Date: 2026-01-09 06:55:25.805833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6298d02803fa'
down_revision: Union[str, Sequence[str], None] = '3dd25ab8d65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quizzes_session_id'), 'quizzes', ['session_id'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'quiz_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_session_id'), table_name='quizzes')
    op.drop_column('quizzes', 'session_id')
    # ### end Alembic commands ###
