"""add question_type column to courses table

Revision ID: 6fc57bad355c
Revises: 87e84685f67f
Create Date: 2025-12-12 18:04:49.897118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc57bad355c'
down_revision: Union[str, Sequence[str], None] = '87e84685f67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('question_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'question_type')
    # ### end Alembic commands ###
