"""remove avatar_url from user-personality table

Revision ID: 8bb80e1591d5
Revises: ceb91b4ec7f3
Create Date: 2026-01-02 02:14:28.000100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb80e1591d5'
down_revision: Union[str, Sequence[str], None] = 'ceb91b4ec7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_personalities', 'avatar_url')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.add_column('user_personalities', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
