"""add hint and memories tip to flashcard table

Revision ID: 8c8e83e81275
Revises: 0c731ce70022
Create Date: 2026-01-06 07:47:02.481538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8e83e81275'
down_revision: Union[str, Sequence[str], None] = '0c731ce70022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('flashcards', sa.Column('memories_tips', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'memories_tips')
    op.drop_column('flashcards', 'hint')
    # ### end Alembic commands ###
