"""change status to process_status of table course

Revision ID: c9083f3c4561
Revises: 3426019b73ff
Create Date: 2025-12-15 00:28:40.076886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9083f3c4561'
down_revision: Union[str, Sequence[str], None] = '3426019b73ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('courses', 'process_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('process_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
