"""add user_id to folder

Revision ID: c97c9d4ed914
Revises: 6298d02803fa
Create Date: 2026-01-09 13:57:44.447340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97c9d4ed914'
down_revision: Union[str, Sequence[str], None] = '6298d02803fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'user_id')
    # ### end Alembic commands ###
