"""modify table document chunk-add embedding column

Revision ID: e9ef75ce8bb1
Revises: 431b1b760333
Create Date: 2025-12-08 16:58:34.709294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e9ef75ce8bb1'
down_revision: Union[str, Sequence[str], None] = '431b1b760333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('token_count', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_vector')
    op.drop_column('document_chunks', 'token_count')
    # ### end Alembic commands ###
